/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OnlineHelp.java
 *
 * Created on Jun 30, 2012, 4:40:00 PM
 */

package cardmanager.gui.impl;

/**
 *
 * @author jvanek
 */
public class OfflineHelp extends javax.swing.JDialog {

    public static final String t=
"CardManager\n"+
"\n"+
"This is free, opensource multiplatform (java) application which allows you to play ANY card game.\n"+
"Only thing you need are images of the cards palced in collections folder. hen you can compose any package you want and play through network or on localhost or with yourself;)\n"+
"\n"+
"Cooperating projects:\n"+
"tripsahre.cz tripsahreterrain jpanoramamaker jscrabble3D mobile pacman mobile snake mobile stoneeater mobile stoneeater mobile tetris\n"+
"\n"+
"Downloads\n"+
"\n"+
"   * runnable application with basic cards images and exempalr packages http://cardmanager.wz.cz/CardManager.zip\n"+
"    * source codes with basic cards images and exemplar packages http://cardmanager.wz.cz/CardManager_sources.zip\n"+
"    * doomtrooper cards imagesc collection with exemplar packages (due to big size of 225MB hosted on download server uloz.to) http://www.uloz.to/8611374/cardmanager-doomtroopercollection-zip\n"+
"\n"+
"\n"+
"Compilation\n"+
"\n"+
"    * Delivered to you as NetBEans project without any dependences\n"+
"\n"+
"Enchanting collections and own packages\n"+
"\n"+
"   * just put any images into collections folder and create pacage from application menu Settings->design package\n"+
"\n"+
"Screenshots\n"+
"\n"+
"Faq\n"+
"\n"+
"  #\n"+
"\n"+
"    Q:How to paly with myself?\n"+
"    A:If you are playng really one-man game, Create an package as usuall and proceed to new game as ususal (settings-network game settings-> start game), \"select I'm server\" But do not wait for anybody and press e\"every body conneected, start game\"\n"+
"  #\n"+
"\n"+
"    Q:How to play mulltiple players on one computer?\n"+
"    A:Proceed to new game as ususal (settings-network game settings-> start game), one of you \"select I'm server\", others fill ip with \"localhost\". Be sure everybody have same port number.Server click start game, the others afterwards also. Then Server Click \"every body conneected, start game\" and you can enjoy hot seat game. But Local network will serve you more comfortably;)\n"+
"  #\n"+
"\n"+
"    Q:Whowk. Thoose selecting actions from popup menus is horribly slow!!\n"+
"    A:Thats why there are those alt+numbers (which does not often work:-/) and numbers. Click menu, and then just number number number.. and You will see how fast actions begun to be!\n"+
"  #\n"+
"\n"+
"    Q:Restarting or new game seams to be not working...\n"+
"    A:Yap. This is about to be bug... Restart aqppliucation. All of attended players:(\n"+
" #\n"+
"\n"+
"    Q:Strange images or 'no image' appears during game\n"+
"    A:It is important that all the players have same (or at least same attended) cards. And also hierarchy in collection MUST be same\n"+
"\n"+
"        Wish you good luck with playing! author - Vaněk  Jiří\n"+
"        email:  judovana@email.cz\n";



    /** Creates new form OnlineHelp */
    public OfflineHelp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try{
        jTextPane1.setText(t);
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OfflineHelp dialog = new OfflineHelp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

}
