/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GlobalSettingsDialog.java
 *
 * Created on 19.10.2010, 17:10:12
 */

package cardmanager.gui;

import cardmanager.FileBearer;
import cardmanager.impl.Settings;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Jirka
 */
public class GlobalSettingsDialog extends javax.swing.JDialog {
    private Settings settings;
    private SelectCardComponent sc;

    private class MyFileOut implements FileBearer{

        File f;

        public MyFileOut(File f) {
            this.f = f;
        }

        public File getFile() {
            return f;
        }

        @Override
        public String toString() {
           return f.getName();
        }

        @Override
        public boolean equals(Object obj) {

        if (!(obj instanceof MyFileOut)) return false;
        MyFileOut mf=(MyFileOut) obj;
        return (mf.toString().equals(this.toString()));
        }

        @Override
        public int hashCode() {

           return  toString().hashCode();
        }





    }
    /** Creates new form GlobalSettingsDialog */
    public GlobalSettingsDialog(java.awt.Frame parent, boolean modal,Settings setting) {
        super(parent, modal);
        this.settings=setting;
        initComponents();
        jCheckBox1.setSelected(settings.getAutoScroll());
        jSpinner1.setModel(new SpinnerNumberModel(settings.getCardWidth().intValue(), 0, 1000, 1));
        jSpinner2.setModel(new SpinnerNumberModel(settings.getCardHeight().intValue(), 0, 1000, 1));
        jSpinner3.setModel(new SpinnerNumberModel(settings.getMarkerRadius().intValue(), 0, 1000, 1));
        jSpinner1.addChangeListener(new ChangeListener() {

            public void stateChanged(ChangeEvent e) {
                settings.setCardWidth(((Number)jSpinner1.getValue()).intValue());
            }
        });

        jSpinner2.addChangeListener(new ChangeListener() {

            public void stateChanged(ChangeEvent e) {
                settings.setCardHeight(((Number)jSpinner2.getValue()).intValue());
            }
        });
         jSpinner3.addChangeListener(new ChangeListener() {

            public void stateChanged(ChangeEvent e) {
                settings.setMarkerRadius(((Number)jSpinner3.getValue()).intValue());
            }
        });

        jTextField1.setText(settings.getName());
        jTextField1.getDocument().addDocumentListener(new DocumentListener() {

            public void insertUpdate(DocumentEvent e) {
                actionPerformed(null);
            }

            public void removeUpdate(DocumentEvent e) {
                actionPerformed(null);
            }

            public void changedUpdate(DocumentEvent e) {
                actionPerformed(null);
            }


            public void actionPerformed(ActionEvent e) {
                settings.setName(jTextField1.getText());
            }
        });
        File f[]=Settings.DEF_BGS.listFiles();
        List<FileBearer> sr=new ArrayList(f.length);
        for (int i = 0; i < f.length; i++) {
            File file = f[i];
            sr.add(new  MyFileOut(file));
        }
        sc=new SelectCardComponent(sr);
        jPanel1.add(sc);
        sc.getList().setSelectedValue(new MyFileOut(new File(settings.getBackground())), true);
        sc.getList().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        sc.getList().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                if (sc.getList().getSelectedValue()==null) return;
         settings.setBackground(sc.getList().getSelectedValue().toString());
            }
        });
        pack();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Playe's name");

        jTextField1.setText("jTextField1");

        jLabel2.setText("Card width");

        jLabel3.setText("Card height");

        jLabel4.setText("Background");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jCheckBox1.setText("auto Scroll");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel5.setText(" Marker Radius");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        settings.setAutoScroll(jCheckBox1.isSelected());
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GlobalSettingsDialog dialog = new GlobalSettingsDialog(new javax.swing.JFrame(), true,new Settings(0));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
