/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CollectionView.java
 *
 * Created on 19.10.2010, 13:58:55
 */

package cardmanager.gui;

import cardmanager.FileBearer;
import cardmanager.impl.card.Card;
import java.util.AbstractList;
import java.util.List;
import java.util.RandomAccess;
import javax.swing.JDialog;


/**
 *
 * @author Jirka
 */
public class SelectcardDialog extends javax.swing.JDialog {
SelectCardComponent sc;
    /** Creates new form CollectionView */
    public SelectcardDialog(java.awt.Frame parent, boolean modal, List<Card> backend) {
        super(parent, modal);
        initComponents();
        sc=new SelectCardComponent(prevent(backend));
        this.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
        this.add(sc);
        sc.setMultipleSellection(false);
        
        this.setSize(800, 600);
      
    }

    public SelectCardComponent getSelectComponent() {
        return sc;
    }

public Object[] getSelected(){
    return sc.getSelected();
}


    public void setMultipleSellection(boolean b){
    sc.setMultipleSellection(b);
}

    Card getSelected1() {
        if (sc.getList().getSelectedIndex()<0) return null;
        return (Card)sc.getSelected()[0];
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectcardDialog dialog = new SelectcardDialog(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private List<FileBearer> prevent(List<Card> backend) {
       return new XList<FileBearer> (backend);
    }

     private static class XList<E> extends AbstractList<E>
	implements RandomAccess, java.io.Serializable
    {
        private static final long serialVersionUID = -2764017481108945198L;
	private final List<Card> a;

	XList(List<Card> array) {
            if (array==null)
                throw new NullPointerException();
	    a = array;
	}

	public int size() {
	    return a.size();
	}

        @Override
	public Object[] toArray() {
	   return a.toArray();
	}

        @Override
	public <T> T[] toArray(T[] a) {
	  return this.a.toArray(a);
	}

	public E get(int index) {
	    return (E)a.get(index);
	}

        @Override
	public E set(int index, E element) {

	    return (E)a.set(index, (Card)element);
	}

        public int indexOf(Object o) {
        return a.indexOf(o);
        }

        public boolean contains(Object o) {
           return a.contains(o);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


 



}
