/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * popuppokus.java
 *
 * Created on 7.12.2010, 16:19:18
 */

package cardmanager;

import cardmanager.gui.impl.Popupizer;
import java.awt.MouseInfo;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

/**
 *
 * @author Jirka
 */
public class popuppokus extends javax.swing.JFrame {

    /** Creates new form popuppokus */
    public popuppokus() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        Popupizer r=new Popupizer();

       JPopupMenu jp=new JPopupMenu("hi");
       JMenuItem jpi1=new  JMenuItem("first item");
       JMenuItem jpi2=new  JMenuItem("second item");
       JMenuItem jp1=new JMenu("middle menu");
       JMenuItem jpi11=new  JMenuItem("first subitem");
       JMenuItem jpi22=new  JMenuItem("second subitem");
       jp1.add(jpi11);
       jp1.add(jpi22);
       jp.add(jpi1);
       jp.add(jp1);
       jp.add(jpi2);

       
       r.addAndInc(jpi1);
       r.addAndInc(jp1);
       r.addAndInc(jpi11);
       r.addAndInc(jpi22);
       r.addAndInc(jpi2);

       if (evt.getButton()==evt.BUTTON1){
       jp.show(this, evt.getX(), evt.getY());
       }else{
           jp.show(null, MouseInfo.getPointerInfo().getLocation().x, MouseInfo.getPointerInfo().getLocation().y);
       }
    }//GEN-LAST:event_formMouseReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popuppokus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
